### PR TITLE
Use access token instead of password

### PR DESCRIPTION
**Pull request by deees**
Fixes
```
132 - You are required to use your Access Token in your Reporter properties file. You may no longer use your username and password in your Reporter properties file
```

@iscreen

### CODE REVIEW

**Comment by zedtux** [comment]
@iscreen can you please have a look and merge this PR? It's blocking us

**Comment by iscreen** [comment]
I've saw the change http://help.apple.com/itc/contentreporterguide/en.lproj/static.html#apd2f1f1cfa3
maybe i should provide generate token feature

**Comment by zedtux** [comment]
Thank you @iscreen ! When do you think you'll release the new version?

**Comment by iscreen** [comment]
0.1.3 has released.

**Pull request merged**
