### PR TITLE
Feature/generate token

### PR DESCRIPTION
**Pull request by porbas**
View & Generate AppleReporter Access Token.
Ported from python implementation https://github.com/fedoco/itc-reporter

### CODE REVIEW

**Comment by porbas** [comment]
@iscreen Are you not interested with this feature?

**Comment by iscreen** [comment]
@porbas 
Yes, I am fine with that, but I've just missed some notifications, 
please give me some time, then I will check your changes.

**Comment by iscreen** [comment]
@porbas 
Why you won't to implement 'deleteToken' ?

**Comment by porbas** [comment]
I didn't notice this `deleteToken` feature - I have no such use case. I'll try to implement it just to have full coverage of provided API

**Comment by iscreen** [comment]
@porbas 
I saw this feature has implemented in python, It's same as `viewToken`,
I just curious why not cover it, If you can cover it that will be great, or I can still merge these first.

**Comment by iscreen** [comment]
@porbas thanks for your contribution.

**Comment by porbas** [comment]
@iscreen thanks for your gem :)

**Pull request merged**
